In [1]:
import pandas as pd
import numpy as np

In [2]:
data =pd.read_csv("car_sales.csv")

In [3]:
data.head()

Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0           1        Acura  Integra    Small       12.9   15.9       18.8   
1           2        Acura   Legend  Midsize       29.2   33.9       38.7   
2           3         Audi       90  Compact       25.9   29.1       32.3   
3           4         Audi      100  Midsize       30.8   37.7       44.6   
4           5          BMW     535i  Midsize       23.7   30.0       36.2   

   MPG.city  MPG.highway             AirBags  ... Passengers Length  \
0        25           31                None  ...          5    177   
1        18           25  Driver & Passenger  ...          5    195   
2        20           26         Driver only  ...          5    180   
3        19           26  Driver & Passenger  ...          6    193   
4        22           30         Driver only  ...          4    186   

   Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
0        102     68           37            26.5         11.0    2705   
1        115     71           38            30.0         15.0    3560   
2        102     67           37            28.0         14.0    3375   
3        106     70           37            31.0         17.0    3405   
4        109     69           39            27.0         13.0    3640   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 28 columns]

In [6]:
price_array =data['Price'].to_numpy()

In [7]:
price_array

array([15.9, 33.9, 29.1, 37.7, 30. , 15.7, 20.8, 23.7, 26.3, 34.7, 40.1,
       13.4, 11.4, 15.1, 15.9, 16.3, 16.6, 18.8, 38. , 18.4, 15.8, 29.5,
        9.2, 11.3, 13.3, 19. , 15.6, 25.8, 12.2, 19.3,  7.4, 10.1, 11.3,
       15.9, 14. , 19.9, 20.2, 20.9,  8.4, 12.5, 19.8, 12.1, 17.5,  8. ,
       10. , 10. , 13.9, 47.9, 28. , 35.2, 34.3, 36.1,  8.3, 11.6, 16.5,
       19.1, 32.5, 31.9, 61.9, 14.1, 14.9, 10.3, 26.1, 11.8, 15.7, 19.1,
       21.5, 13.5, 16.3, 19.5, 20.7, 14.4,  9. , 11.1, 17.7, 18.5, 24.4,
       28.7, 11.1,  8.4, 10.9, 19.5,  8.6,  9.8, 18.4, 18.2, 22.7,  9.1,
       19.7, 20. , 23.3, 22.7, 26.7])

In [8]:
price_mean =np.mean(price_array)

In [9]:
price_mean

19.50967741935484

In [10]:
price_max = np.max(price_array)
price_max

61.9

In [14]:
price_2d = np.reshape(price_array, (len(price_array), 1))
price_2d

array([[15.9],
       [33.9],
       [29.1],
       [37.7],
       [30. ],
       [15.7],
       [20.8],
       [23.7],
       [26.3],
       [34.7],
       [40.1],
       [13.4],
       [11.4],
       [15.1],
       [15.9],
       [16.3],
       [16.6],
       [18.8],
       [38. ],
       [18.4],
       [15.8],
       [29.5],
       [ 9.2],
       [11.3],
       [13.3],
       [19. ],
       [15.6],
       [25.8],
       [12.2],
       [19.3],
       [ 7.4],
       [10.1],
       [11.3],
       [15.9],
       [14. ],
       [19.9],
       [20.2],
       [20.9],
       [ 8.4],
       [12.5],
       [19.8],
       [12.1],
       [17.5],
       [ 8. ],
       [10. ],
       [10. ],
       [13.9],
       [47.9],
       [28. ],
       [35.2],
       [34.3],
       [36.1],
       [ 8.3],
       [11.6],
       [16.5],
       [19.1],
       [32.5],
       [31.9],
       [61.9],
       [14.1],
       [14.9],
       [10.3],
       [26.1],
       [11.8],
       [15.7],
       [19.1],
       [21

In [ ]:
# Calculate the correlation coefficient between two columns
sales_col = data['Sales'].to_numpy()
profit_col = data['Profit'].to_numpy()
correlation = np.corrcoef(sales_col, profit_col)

# Perform element-wise arithmetic operations on arrays
discounts = data['Discount'].to_numpy()
adjusted_prices = sales_col - discounts


In [16]:
min_price_col = data['Min.Price'].to_numpy()
max_price_col = data['Max.Price'].to_numpy()
correlation = np.corrcoef(min_price_col,max_price_col)
correlation

array([[1.        , 0.90675608],
       [0.90675608, 1.        ]])

In [17]:
# Create a new array filled with zeros
zeros_array = np.zeros((10, 5))

# Create an array with random values
random_array = np.random.rand(100)

# Reshape an array
reshaped_array = random_array.reshape((10, 10))

# Transpose an array
transposed_array = reshaped_array.T


In [18]:
np.save('price_array.npy', price_array)
