In [1]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
print(a[0])

[1 2 3 4]


In [5]:
print(a[2])

[ 9 10 11 12]


In [6]:
a = np.array([1, 2, 3])

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.zeros(0)

array([], dtype=float64)

In [9]:
np.empty(2)

array([0., 0.])

In [10]:
np.empty(3)

array([ 6.89798700e-307,  1.28651375e-311, -0.00000000e+000])

In [12]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [13]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [15]:
np.arange(2,10,4)

array([2, 6])

In [17]:
a=(4,1,6,8,3,5,9)
np.sort(a)

array([1, 3, 4, 5, 6, 8, 9])